### ISSUE TITLE
Get file icon on windows

### ISSUE THREAD

**Issue by KELiON** [KELiON/cerebro#16]
Find a way to read file icon on Windows

**Comment by SkaceKamen** [comment]
I was able to read file icons on windows using binary written in C# which extracts the icon and returns their base64 contents, which is same principle as `icon-extractor` is trying to use.

This is probably the worst solution, because:
 - said binary file must be included in the application
 - despite being only 100 lines of code in C#, it's still part written in another language
 - it introduces .NET dependency

But it works and it's the simplest solution.

I'm currently looking into using `node-ffi`, which would be much better.

**Comment by SkaceKamen** [comment]
I've made solution that uses node-ffi, so no .NET dependency!

You can find it here: https://github.com/SkaceKamen/win-icon-extractor

I've already successfully integrated it into cerebro, but need some time to polish it.

**Comment by toXel** [comment]
There is another open-source electron launcher like cerebro called Hain and there the icons on Windows work wonderful. For me it looks like a very simple approach: https://github.com/appetizermonster/hain/blob/master/app/main/plugins/hain-plugin-filesearch/win32/search-util.js#L7-L12

**Comment by SkaceKamen** [comment]
It's very similiar approach I'm using, the "icon://" protocol is not builtin of electron, but it's defined here:
https://github.com/appetizermonster/hain/blob/master/app/main/server/app/icon-protocol.js
which calls this C code:
https://github.com/appetizermonster/hain/blob/master/app/native/platform-util/addon.cc
which is very similiar to my approach.

**Comment by toXel** [comment]
Ah I see ok sorry then. I thought it's way easier :D but I haven't looked that deep into the code.

**Comment by SkaceKamen** [comment]
I actually hoped it that simple, it would make things easier :D
