### ISSUE TITLE
Vim like movement keys

### ISSUE THREAD

**Issue by mijoharas** [KELiON/cerebro#170]
Hi, just installed cerebro and I have to say that I'm quite enjoying it. I was opening this issue to check whether you'd be happy for me to implement a feature that I would quite like to have.

I use spacemacs and vimium and am quite used to using vim-like command keys to navigate around. I was wondering if it would be ok for me to add these to cerebro.

For instance, `Ctrl+j` would go down `Ctrl+k` would go up, `Ctrl+h` would go left and `Ctrl+l` would go right.

If it's not wanted generally we could put them behind a feature flag in the settings. What do you think?

**Comment by maximbaz** [comment]
I'd love to see such alternative shortcuts. I personally think there is no reason to hide them behind a feature flag, as currently they do nothing.

**Comment by KELiON** [comment]
I'd just add j/k/l/h hotkeys (without ctrl), but I'm not sure what to do with input focus. In this case we should introduce two modes (like in vim). Now I see only one way is to add another flag to settings. If this flag is on, then:

1) When you open Cerebro window it is in insert mode
2) After you input something and use <kbd>esc</kbd> it switches to command mode
3) In command mode j/k/l/h keys are used for navigation, <kbd>o</kbd> is equal of <kbd>enter</kbd>, <kbd>i</kbd> switches back to insert mode, <kbd>esc</kbd> closes the window. 

What do you think, @maximbaz @mijoharas?

**Comment by maximbaz** [comment]
A whole separate mode is no doubt a much more powerful concept, I'm sure there will be other ideas what could we do in the command mode apart from navigating with <kbd>jklh</kbd>.

Just one wish: do not make <kbd>esc</kbd> from command mode close the window, let it better be <kbd>q</kbd>. 

I'm used too much to the fact that hitting <kbd>esc</kbd> multiple times in vim does not hurt and just keeps me in normal mode. Even if I'm in normal mode already, due to my muscle memory I sometimes hit <kbd>esc</kbd> again (to be sure that I'm in normal mode) and then begin navigating with <kbd>jklh</kbd> — I don't want this to close the window 🙂

**Comment by shkm** [comment]
Would love this.

On a related note, the Emacs-like ctrl+p / ctrl+n for up and down respectively would be great. These shortcuts are prevalent throughout OS X, though I'm running Cerebro on a Linux box and I miss them (coming from Alfred). Different issue?

**Comment by mijoharas** [comment]
:+1: command mode is even better in my opinion, as that's nice and natural to me. Thanks!

**Comment by troglotit** [comment]
I'd vote for hybrid-mode: Ctrl-h/j/k/l Ctrl-n/p (and maybe ctrl-f/b). Introducing modes to an app is such a burden from maintenance point of view.

**Comment by maximbaz** [comment]
It doesn't have to be one or another, the shortcuts <kbd>Ctrl+j/k/h/l/n/p</kbd> are unused now and can be added right away, for everyone, not controlled by any settings - and for some people that would be enough.

The command mode is a different beast, it has to be hidden in the settings and disabled by default, otherwise people will just be confused a lot. But it potentially provides much more control than a simple navigation.

**Comment by KELiON** [comment]
I like this idea of having mixed shortcuts, like lightweight vim-mode and hardcore vim-mode hidden in settings! In this case everyone should be happy:)

**Comment by KELiON** [comment]
Ok, summarizing: 

There are two steps of implementation.

### Lightweight vim-mode
On first step we just add few more shortcuts:
<kbd>ctrl+hjkl</kbd> – navigate in results (the same as arrows now)
<kbd>ctrl+o</kbd> – select (=== <kbd>enter</kbd>)

### Hardcore vim-mode
* We add a checkbox to settings to active this feature
* We introduce two modes:

#### Insert mode
It works, like Cerebro works now. Only one exception <kbd>esc</kbd> switches app to command mode, instead of closing the window

#### Command mode
In this mode you can't change input term, but you have more powerfull commands, like

<kbd>hjkl</kbd> – navigate in results (the same as arrows in insert mode)
<kbd>o</kbd> – select (=== <kbd>enter</kbd>)
<kbd>i</kbd> – switch app back to insert mode
<kbd>q</kbd> – close the window

Any more thoughts?

**Comment by KELiON** [comment]
So, first stage is out in release 0.2.8
