### ISSUE TITLE
~ is not recognized under Windows  

### ISSUE THREAD

**Issue by tmueller** [KELiON/cerebro#298]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.0.15063 Build 15063 Microsoft Windows 10 Pro
- **Cerebro.app version**: 0.2.8

## Issue

Cerebro picks up file paths when starting the input with "/" or "\~". Unfortunately only "/" works under windows. The reason might be, that there is no native OS support for "\~". But it could easily be emulated and would be very helpful for Windows users.

**Comment by KELiON** [comment]
@tmueller I've just checked code and I think I understand, why it doesn't work. We already change `~` to real user path, but later we [check the input](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/files/index.js#L32). But since windows full path starts with partition name (like `C:`, `D:`, etc), so we should change this check for windows machines.

I'd appreciate PR from someone on windows machine for that. Thanks for report!

**Comment by Seldaek** [comment]
@KELiON can you update the link to "check the input" in your comment above? It's 404'd, but if you give a good pointer I might have a look at sending a PR for this.

**Comment by KELiON** [comment]
@Seldaek sure, this plugin was moved to separate repo. So, problem is:

1) [Here](https://github.com/KELiON/cerebro-files-nav/blob/master/src/index.js#L30) we replace `~` with user home path 
2) But [after thathere](https://github.com/KELiON/cerebro-files-nav/blob/master/src/index.js#L34) we check that path matches regexp. 

So, probably on windows user home path contains partition (C:, D:, etc), and after replacing this path (i.e. `C:/Users/<me>/...` doest match regexp `const DIR_REGEXP = /^\/(.*\/)*(.*)/`
