### ISSUE TITLE
Windows 10 icons bug

### ISSUE THREAD

**Issue by TheAresjej** [KELiON/cerebro#347]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 v1703 (Build 15063.413)
- **Cerebro.app version**: 0.3.0

## Issue
Screen: http://imgur.com/a/1t1BF
Icons: This PC / Control panel / Inno Setup Compiler / Intel XDK / Discord

**Comment by maferland** [comment]
I would like to look at this bug. Any hint on where to start looking ?

**Comment by KELiON** [comment]
@maferland [cerebro-basic-apps](https://github.com/KELiON/cerebro-basic-apps/blob/master/src/windows.js#L7) uses path to file as icon. Later we use `FileIcon` component from `cerebro-ui` to [get image](https://github.com/KELiON/cerebro-ui/blob/master/src/FileIcon/getFileIcon/windows.js), so you can check it. You can also ask @SkaceKamen for help, since he implemented current version in #16
