### ISSUE TITLE
Tray icon color (windows) 

### ISSUE THREAD

**Issue by AlexAlabyev** [KELiON/cerebro#36]
It's better to change the color of the tray icon to white

![capture1](https://cloud.githubusercontent.com/assets/13764106/22333331/b6ed4c7a-e3e6-11e6-8ae3-d9ec9cb6fdc8.PNG)

Download image (96% white):
![tray_icontemplate 2x](https://cloud.githubusercontent.com/assets/13764106/22333335/c4a6e0ce-e3e6-11e6-95ba-94d4912fd8e5.png) 
[image](https://cloud.githubusercontent.com/assets/13764106/22333335/c4a6e0ce-e3e6-11e6-95ba-94d4912fd8e5.png)

**Comment by wstarcev** [comment]
Gnome Shell dark theme vote +1 for white color too.

**Comment by KELiON** [comment]
@AlexAlabyev thanks for report! 

I'll check how to apply it for dark-only windows and linux, but as I understand now, dark/light icon switching in electron [works only on mac](https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image). 

Since I use only mac, my questions for windows users: is it ok to show in tray not black and white icon, but just [usual app icon](https://github.com/KELiON/cerebro/blob/master/build/icons/32x32.png)?

**Comment by niittymaa** [comment]
@KELiON I think it's valid way to use color icon if I compare to the others in my tray :)

![trayicons png](https://cloud.githubusercontent.com/assets/4587998/22457253/61c49638-e79f-11e6-8cd8-e9fd6f639621.png)

**Comment by KELiON** [comment]
@niittymaa got it! Thanks:)
