### ISSUE TITLE
nice screenshots, what's with the tracking?

### ISSUE THREAD

**Issue by kylepwarren** [KELiON/cerebro#398]
why?

https://github.com/KELiON/cerebro/pull/345/files

**Comment by kylepwarren** [comment]
Does this just track npm usage? seems like a lot of the electron apps are invasive. Track personal stuff. Seems like I saw in a comment somewhere that this[cerebro] has that problem. Is it true? if so, can you stop? I stopped using atom for that reason, mostly. Also atom, though has cool plug-ins, mostly remote support, still kind of sucks. plenty of important things just don't work. auto indentation. Making it not better than a lot of things.

**Comment by KELiON** [comment]
@kylepwarren it doesn't collect any personal information, just information about some application events. How often users use mouse and clicks and how often they do it with keyboard. What plugins are used more. With this information we can improve UX of the application. And it is not to collect any personal stuff. Also, since it is open-source you can always check in source code, what is tracked and what is not. 

If the way of your usage of this app is so personal for you, I don't mind if you create pull-request to add checkbox in settings that switches tracking. Let me know if I can help you with code base

**Comment by KELiON** [comment]
BTW, there is already an issue for that: #392

**Comment by gerroon** [comment]
Is this implemented? I do not see a setting for disabling tracking? 

>How often users use mouse and clicks and how often they do it with keyboard. What plugins are used more.


This is as personal as gets, not sure why the developers do not think that this is a bit creepy, you are literally watching someone doing stuff in realtime.

**Comment by ChFlick** [comment]
> Is this implemented? I do not see a setting for disabling tracking?
> 
> > How often users use mouse and clicks and how often they do it with keyboard. What plugins are used more.
> 
> This is as personal as gets, not sure why the developers do not think that this is a bit creepy, you are literally watching someone doing stuff in realtime.

https://github.com/cerebroapp/cerebro/commit/8d2369f1c05e56bbd4f620677af12f91c31af53d
https://github.com/cerebroapp/cerebro/issues/512
