### ISSUE TITLE
Ubuntu16.04 App image doesn't open.

### ISSUE THREAD

**Issue by yusunglee2074** [KELiON/cerebro#431]
- [ x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:16.04 Ubuntu
- **Cerebro.app version**: cerebro-0.3.2-x86_64
- **Relevant information from devtools** _(See above how to open it)_: can't open.

I downloaded 0.3.2 App image.

And make excutable.

Run with ./cerebro-0.3.2-x86_64.appimage

But... i got this error...

https://imgur.com/a/VR0fs
https://imgur.com/a/qXMYw
https://imgur.com/a/NS1lS

After three successive errors.

Launch with ctrl + space.
Cant got anything.
 
https://imgur.com/geXEQMq

And ...amd64.deb got exactly same error message and bug.

Last Thanx for this great program.

**Comment by lawgsy** [comment]
Ah yes, I noticed this yesterday on Windows as well - this is a cross-platform issue and I'm sure @KELiON will re-release to fix this once he has the time.

Related: https://github.com/KELiON/cerebro/issues/423, this was fixed in https://github.com/KELiON/cerebro/commit/b379a5b90ba63df99155210ef043d69ae785e6a6 but *somehow* **snuck into the release build**.

If you're feeling adventurous you should be able to build from source or you can just wait until the next (hot-fix) release.

**Comment by yusunglee2074** [comment]
Thank you.
