### ISSUE TITLE
How install cerebro plugin with command line?

### ISSUE THREAD

**Issue by fabiovanderlei** [KELiON/cerebro#441]
How install cerebro plugin with command line?

**Comment by lawgsy** [comment]
See https://github.com/KELiON/cerebro/issues/220 (but use `yarn` instead of `npm` now for package management). Assuming the plugin is published, you can:

Open a terminal at the directory the `config.json` is in
Windows: `%APPDATA%/Cerebro/config.json`
Linux: `$XDG_CONFIG_HOME/Cerebro/config.json` or `~/.config/Cerebro/config.json`
macOS: `~/Library/Application Support/Cerebro/config.json`

Then:
1. `cd ./plugins`
2. `yarn add plugin-name-here`

If the plugin is not published, you should be able to simply extract the contents into the `Cerebro/plugins/plugin-name-here` directory. Or create a symlink to where it is located.

**Comment by Qiamast** [comment]
**very help full**

>
