### ISSUE TITLE
App search by abbreviation not working

### ISSUE THREAD

**Issue by vandamm** [KELiON/cerebro#65]
Cerebro should be able to search for applications using first letters (ie searching for lol should yield League of Legends). Spotlight does this.

![screen shot 2017-02-01 at 09 33 52](https://cloud.githubusercontent.com/assets/576786/22497902/d1200b68-e865-11e6-85a1-ed8aee1449f1.png)
![screen shot 2017-02-01 at 09 33 45](https://cloud.githubusercontent.com/assets/576786/22497261/6f27c76a-e861-11e6-8e7d-db7491f62ac0.png)

**Comment by KELiON** [comment]
@vandamm wow, never knew that. It worth to be added!

**Comment by maximbaz** [comment]
I wonder if we could use [fzf](https://github.com/junegunn/fzf) to do a fuzzy search on everything, imagine how cool that would be!

**Comment by elmerehbi** [comment]
Has fuzzy search been implemented in the latest release? I typed "thnder" to open thunderbird but it doesn't display it.

Also on Linux (Ubuntu Gnome) it can't find "totem".

**Comment by KELiON** [comment]
@elmerehbi no, fuzzy search is not included. I'm still thinking about it, because I'm afraid it could generate a lot of noise. So, currently to find `thunderbird` you should start your search with `thun...`. Another way works only if app name contains a space of have CamelCase (like `ThunderBird`). In this case you can use `tb` to find it

**Comment by aleclarson** [comment]
+1

If fuzzy-finding is too noisy, we could still find a way to get `sys pref` to select System Preferences. Seems like this would be simple enough to add.
